# Generated by Django 4.0.2 on 2023-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookpage',
            field=models.FileField(null=True, upload_to='bookpage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.FileField(null=True, upload_to='coverpage/'),
        ),
    ]
