# Generated by Django 4.0.2 on 2023-04-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
    ]
